### ISSUE TITLE
Configurações botões

### ISSUE THREAD

**Issue by tothfabio** [miuibrasil/MIUIBrasil-8-XML-for-Xiaomi.eu#4]
Ao entrar no menu de configurações dos botões ocorre force close do app no Redmi Note 3
 Segue abaixo o código de erro:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 4
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$900(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 4
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.remove(ArrayList.java:403)
	at com.android.settings.KeySettings.onCreate(KeySettings.java)
	at android.app.Fragment.performCreate(Fragment.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.BackStackRecord.run(BackStackRecord.java)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
	at com.android.settings.ho.a(SettingsActivity.java)
	at com.android.settings.ho.onCreate(SettingsActivity.java)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 10 more

**Comment by mattbittencourt** [comment]
Olá Fábio,

O problema ocorre pois a tradução da ROM estava incompleta durante a compilação desta última semana. Na sexta-feira já estará solucionado.

Obrigado!

**Comment by tothfabio** [comment]
Fenomenal!!! Ótimo trabalho!!!! Vcs são sensacionais. Abraços.

Em 20 de set de 2016 11:21 PM, "Matheus R. Ferreira" <
notifications@github.com> escreveu:
